First pass on implementing Bookings
MarySalemme/makersbnb pull request #28
Opened 2017-07-12 12:50 UTC by tbscanlon

Right now they go into the DB. They're not yet displayed anywhere however.

The form is implemented too but it's very basic

2017-07-12 12:55 UTC, Corina commented on app/controllers/bookings.rb
> +    finish = Date.parse(params[:end_date])
maybe a test with the app/ look in db before using parse

2017-07-12 12:58 UTC, Corina commented on app/views/bookings/new.erb
> +  <input type="text" name="space_id" value="" placeholder="space if">
placeholder should be space id?

2017-07-12 13:00 UTC, Corina commented on spec/backend/features/booking_spaces_spec.rb
> +    expect(Booking.count).to eq 1
extra test

2017-07-12 13:01 UTC, corina requested changes
🍔

2017-07-12 16:18 UTC, vhonebon1 commented on app/views/bookings/new.erb
> +  <input type="text" name="space_id" value="" placeholder="space id">
agreed this will be taken out

2017-07-12 16:24 UTC, vhonebon1 approved these changes
comment refers to line that will be removed at a later date

2017-07-12 17:22 UTC, marysalemme approved these changes

2017-07-13 11:11 UTC, Corina commented on app/controllers/bookings.rb
> +    booking_error("You need to be signed in to book a space") unless current_user
wrap the 3 errors in a method

2017-07-13 11:18 UTC, corina requested changes
GG!

2017-07-13 11:31 UTC, merged